### ISSUE TITLE
水印绕过

### ISSUE THREAD

**Issue by 0xr0ot** [YanxinTang/Watermark#1]
使用浏览器插件，拦截下Watermark.min.js这个就绕过了

**Comment by YanxinTang** [comment]
可以检测`Watermark`这个类来决定页面内容是否显示
```javascript
if (typeof Watermark === 'undefined') {
  // show warning
  // hide page content
}
```

这个库主要是提供一种快速生成文字水印的方式。水印检活这个工作我觉得并不是能轻松解决的，而且也不是这个库所要解决的主要问题，当然如果你有想法可以评论一起讨论。
