### ISSUE TITLE
水印可以切换显示或隐藏状态吗

### ISSUE THREAD

**Issue by Loving-Vincent** [YanxinTang/Watermark#4]
我现在的做法是进页面的时候初始化一个 watermark 对象，然后用的时候去 `set()` 然后 `draw()` 。隐藏的时候直接调用的 `destory()` ，但是这样频繁的销毁然后再set、draw是不是不太好。

还有就是想提醒你一下，你的 **_destory_** 拼错了，销毁的正确拼写是 **_destroy_** 。。。

**Comment by YanxinTang** [comment]
https://jsfiddle.net/tyx1703/8g496sua/6/

1. 可以参考一下这个例子。
需要注意的是，创建`Watermark`实例的时候，把 `auto` 和 `observe` 设置为 `false`

2. 非常感谢指出拼写错误

**Comment by Loving-Vincent** [comment]
感谢提供思路😄，但我还是想在水印展示的时候也可以打开observe的。
我是在react项目里用的，现在的实现思路是把水印打在父级上，切换子元素的隐藏展示并且控制父级背景是否有水印。
子元素是三元表达式控制的是否显示，如果把水印打在子元素上，我怕react还没有render元素，watermark去操作元素的会报错。

**Comment by YanxinTang** [comment]
https://github.com/YanxinTang/Watermark/blob/master/src/Watermark.js#L210

参考这个，可以自己实现 observer，很简单

**Comment by Loving-Vincent** [comment]
好的，多谢。
